---
# inventory:
#   plugin: SimpleInventory
#   options:
#     host_file: "inventory/hosts.yaml"
#     # group_file: "inventory/groups.yaml"
#     # defaults_file: "inventory/defaults.yaml"
inventory:
  plugin: AnsibleInventory
  options:
    hostsfile: "ansible-inventory.yml"
runner:
  plugin: threaded
  options:
    num_workers: 100
