---
interface:
  - name: ethernet-1/1
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv4:
          admin-state: enable
          unnumbered:
            admin-state: enable
            interface: system0.0
  - name: ethernet-1/2
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv4:
          admin-state: enable
          unnumbered:
            admin-state: enable
            interface: system0.0
  - name: ethernet-1/3
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv4:
          admin-state: enable
          unnumbered:
            admin-state: enable
            interface: system0.0
  - name: ethernet-1/4
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv4:
          admin-state: enable
          unnumbered:
            admin-state: enable
            interface: system0.0

network-instance:
  - name: default
    interface:
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0
      - name: ethernet-1/4.0
      - name: system0.0
    protocols:
      isis:
        instance:
          - name: underlay
            admin-state: enable
            level-capability: L2
            max-ecmp-paths: 4
            ipv4-unicast:
              admin-state: enable
            interface:
              - interface-name: ethernet-1/1.0
                circuit-type: point-to-point
                ipv4-unicast:
                  admin-state: enable
                level:
                  - level-number: 2
              - interface-name: ethernet-1/2.0
                circuit-type: point-to-point
                ipv4-unicast:
                  admin-state: enable
                level:
                  - level-number: 2
              - interface-name: ethernet-1/3.0
                circuit-type: point-to-point
                ipv4-unicast:
                  admin-state: enable
                level:
                  - level-number: 2
              - interface-name: ethernet-1/4.0
                circuit-type: point-to-point
                ipv4-unicast:
                  admin-state: enable
                level:
                  - level-number: 2
              - interface-name: system0.0
                admin-state: enable
                passive: true
                ipv4-unicast:
                  admin-state: enable
                level:
                  - level-number: 2
