---
interface:
  - name: system0
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv4:
          admin-state: enable
          address:
            - ip-prefix: 169.254.0.1/32

network-instance:
  - name: default
    protocols:
      isis:
        instance:
          - name: underlay
            net:
              - 49.0001.0000.0000.0001.00
      bgp:
        admin-state: enable
        autonomous-system: 64999
        router-id: 169.254.0.1
        afi-safi:
          - afi-safi-name: evpn
            admin-state: enable
          - afi-safi-name: ipv4-unicast
            admin-state: disable
        group:
          - group-name: evpn-overlay-rr
            export-policy: all
            import-policy: all
            peer-as: 64999
            route-reflector:
              client: true
              cluster-id: 169.254.0.0
            timers:
              minimum-advertisement-interval: 1
            transport:
              local-address: 169.254.0.1
        neighbor:
          - peer-address: 169.254.1.1
            peer-group: evpn-overlay-rr
          - peer-address: 169.254.1.2
            peer-group: evpn-overlay-rr
          - peer-address: 169.254.1.3
            peer-group: evpn-overlay-rr
          - peer-address: 169.254.1.4
            peer-group: evpn-overlay-rr